---
output:
  knitrBootstrap::bootstrap_document:
    title: "Preparing for The First Class"
    theme: amelia
    highlight: sunburst
    theme.chooser: TRUE
    highlight.chooser: TRUE
---

Welcome to STAT 217 class. The following instructions on how to install R and RStudio is extracted and modified a bit from your main course pack, which can be downloaded for free at [MSU Library website](https://scholarworks.montana.edu/xmlui/handle/1/2999).

# Installing R

* Visit the [Comprehensive R Archive Network](https://cran.r-project.org/) (CRAN)
* In the Download and Install R section, you can click on the link that corresponds to your system (Linux, Mac, or Windows).

## On Windows
* Click on **base**.
* Click on **Download R 3.3.1 for Windows** to download the executable file then open that file to start the installation.
* The installation should be straightforward. You can choose the displayed language, installation location on your disk, and the components. Leaving them at default will work for most of you.
* Click **Finish** to end the installation of R.

## On Mac OS X
* Scroll down a little bit, you will see some download links designed for different version of your OS. If you have Mac OS X 10.9 (Mavericks) or higher, choose **R-3.3.1.pkg**. If your OS version is older than that, there is a link of an older version of R right below it.
* Once it is downloaded, double-click on the installer. You may take all of the defaults.

## On Linux Systems
* After clicking **Download R for Linux**, you will be shown different folders for different Linux distros. Select your distro, and proceed as directed.

# Installing RStudio
You will not use R directly in this course. Its UI is very basic and not beautiful. Instead, you will use RStudio, an enhanced interface that will make interacting with R less frustrating.

* Go to [RStudio download page](https://www.rstudio.com/products/rstudio/download3/). We will use the Free License Desktop version. Download the appropriate installer for your operating system (Windows, Mac OS X, or Linux).
* Once it is downloaded, run the RStudio installer and take all of the defaults: In Windows, double-click on the RStudio installer to start the installation; in Mac OS X, double-click on the downloaded RStudio disk-image file, and drag the *RStudio* icon to the *Applications* folder.
*  When you first run RStudio (in Windows, if you don't see the *RStudio* icon on the desktop, click on Start icon and type in `rstudio` in the search box), it should detect your R installation and start the R console.  
* To configure RStudio to your taste, select *Tools > Global Options* (Windows) or *RStudio > Preferences* (Mac OS X) from the RStudio menus. In particular, I suggest that on the *General* options screen you **deselect** *Restore .RData into workspace at startup*, and set *Save workspace to .RData on exit* to **Never**. 


